const mainMenu = document.createElement("div");
const menu = () => {

    const menu = document.querySelector("#mainContainer"); 
    mainMenu.setAttribute("id", "mainMenu");
    const menu1 = document.createElement("div");
    const image1 = document.createElement("div");
    image1.setAttribute("id", "image1");
    const header1 = document.createElement("h1");
    header1.textContent = "Salsiccia";
    const para1 = document.createElement("div");
    para1.textContent = "Tomato sauce, Mozarella,";
    const param1 = document.createElement("div");
    param1.textContent = "Tomato, Homemade";
    const paragraph1 = document.createElement("div");
    paragraph1.textContent = "sausage, Garlic, Basil";
    menu1.setAttribute("id", "menu");
    menu1.append(image1, header1, para1, param1, paragraph1);
    const menu2 = document.createElement("div");
    const image2 = document.createElement("div");
    image2.setAttribute("id", "image2");
    const header2 = document.createElement("h1");
    header2.textContent = "Gamberi";
    const para2 = document.createElement("div");
    para2.textContent = "Tomato sauce, Mozarella,";
    const param2 = document.createElement("div");
    param2.textContent = "Shrimps, Feta cheese,";
    const paragraph2 = document.createElement("div");
    paragraph2.textContent = "Olives, Basil";
    menu2.setAttribute("id", "menu");
    menu2.append(image2, header2, para2, param2, paragraph2);
    const menu3 = document.createElement("div");
    const image3 = document.createElement("div");
    image3.setAttribute("id", "image3");
    const header3 = document.createElement("h1");
    header3.textContent = "Pepe";
    const para3 = document.createElement("div");
    para3.textContent = "Tomato sauce, Mozarella,";
    const param3 = document.createElement("div");
    param1.textContent = "Chilli flakes, Olives, Basil";
    const paragraph3 = document.createElement("div");
    paragraph3.textContent = "sausage, Garlic, Basil";
    menu3.setAttribute("id", "menu");
    menu3.append(image3, header3, para3, param3, paragraph3);
    const menu4 = document.createElement("div");
    const image4 = document.createElement("div");
    image4.setAttribute("id", "image4");
    const header4 = document.createElement("h1");
    header4.textContent = "Disgustoso";
    const para4 = document.createElement("div");
    para4.textContent = "Tomato sauce, Bacon,,";
    const param4 = document.createElement("div");
    param4.textContent = "Pineapple, Olives, Basil";
    const paragraph4 = document.createElement("div");
    paragraph4.textContent = "sausage, Garlic, Basil";
    menu4.setAttribute("id", "menu");
    menu4.append(image4, header4, para4, param4, paragraph4);
    const menu5 = document.createElement("div");
    const image5 = document.createElement("div");
    image5.setAttribute("id", "image5");
    const header5 = document.createElement("h1");
    header5.textContent = "Colorato";
    const para5 = document.createElement("div");
    para5.textContent = "Tomato sauce, Mozarella,";
    const param5 = document.createElement("div");
    param5.textContent = "Onion, Pepper,";
    const paragraph5 = document.createElement("div");
    paragraph5.textContent = "Champignons, Basil";
    menu5.setAttribute("id", "menu");
    menu5.append(image5, header5, para5, param5, paragraph5);
    const menu6 = document.createElement("div");
    const image6 = document.createElement("div");
    image6.setAttribute("id", "image6");
    const header6 = document.createElement("h1");
    header6.textContent = "Pomodoro";
    const para6 = document.createElement("div");
    para6.textContent = "Tomato sauce, Mozarella,";
    const param6 = document.createElement("div");
    param6.textContent = "Tomato, Onion, Feta cheese,";
    const paragraph6 = document.createElement("div");
    paragraph6.textContent = "Chilli";
    menu6.setAttribute("id", "menu");
    menu6.append(image6, header6, para6, param6, paragraph6);
    const menu7 = document.createElement("div");
    const image7 = document.createElement("div");
    image7.setAttribute("id", "image7");
    const header7 = document.createElement("h1");
    header7.textContent = "Crema";
    const para7 = document.createElement("div");
    para7.textContent = "White sauce, Mozarella,";
    const param7 = document.createElement("div");
    param7.textContent = "Shrimps, Salmon,";
    const paragraph7 = document.createElement("div");
    paragraph7.textContent = "Pineapple, Olives, Basil";
    menu7.setAttribute("id", "menu");
    menu7.append(image7, header7, para7, param7, paragraph7);
    const menu8 = document.createElement("div");
    const image8 = document.createElement("div");
    image8.setAttribute("id", "image8");
    const header8 = document.createElement("h1");
    header8.textContent = "Carne";
    const para8 = document.createElement("div");
    para8.textContent = "Tomato sauce, Mozarella,";
    const param8 = document.createElement("div");
    param8.textContent = "Homemade sausage, Bacon,";
    const paragraph8 = document.createElement("div");
    paragraph8.textContent = "Garlic, Pepper, Chilli";
    menu8.setAttribute("id", "menu");
    menu8.append(image8, header8, para8, param8, paragraph8);
    mainMenu.append(menu1, menu2, menu3, menu4, menu5, menu6, menu7, menu8);
    menu.append(mainMenu)
    mainMenu.style.display = 'none';
}

export {menu, mainMenu}